#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: localhost
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Soft-link Ansible Files
  hosts: CentOS,Fedora,RedHat
  become: True
  tasks:
      - file:
            src: "/usr/bin/{{item}}"
            dest: "/usr/local/bin/{{item}}"
            state: link
        loop:
            - ansible
            - ansible-console
            - ansible-doc
            - ansible-galaxy
            - ansible-playbook
            - ansible-pull
            - ansible-vault

- name: Update Hosts File
  hosts: localhost
  become: True
  tasks:
      - lineinfile:
            dest: /etc/hosts
            line: "{{item}}"
        with_items:
            - "127.0.0.1 mongo mongodb redis mysql rabbitmq postgresql"
            - "192.168.100.124 logfaces-boston"
            - "192.168.100.127 mongo1"
            - "192.168.100.134 lds"
            - "192.168.100.183 mongo2"
            - "192.168.254.28 rabbit-test"
            - "192.168.255.29 stagetwo"
            - "192.168.254.48 cd7"
            - "192.168.254.57 mongo1test"
            - "192.168.254.58 docker1test magni"
            - "192.168.254.59 cd6"
            - "192.168.254.63 mongo2test"
            - "192.168.254.73 mli-forever"
            - "192.168.254.81 cd1"
            - "192.168.254.85 cd0"
            - "192.168.254.114 cd5"
            - "192.168.254.123 logfaces"
            - "192.168.255.16 al-autotest-edge"
            - "192.168.255.18 al-autotest-integration"
            - "192.168.254.90 utilite1"
            - "192.168.254.107 moldeutiltest"
            - "192.168.254.28 rmq1test"
            - "192.168.254.73 moldetest"
            - "192.168.254.54 tlo_util"


- name: Create Source Folders
  hosts: localhost
  become: False
  tasks:
      - file:
            path: "/home/vagrant/Bitbucket/{{item}}"
            state: directory
            owner: vagrant
            group: vagrant
        loop:
            - Asgard
            - Gradle
            - Mold-E
            - Sush-E
            - Operations
            - Asgard-Light
            - Slurp-E

- name: Install GitHub Projects
  hosts: localhost
  become: False
  tasks:
    - file:
          path: "/home/vagrant/bin"
          state: directory
    - git:
          repo: https://github.com/kurron/docker-compose-tl.git
          dest: "/home/vagrant/bin/servers"
    - git:
          repo: https://github.com/kurron/docker-compose-tl.git
          dest: "/home/vagrant/GitHub/docker-compose-tl"

- name: Docker Firewall Rules
  hosts: CentOS,Fedora,RedHat
  become: True
  tasks:
    - package:
          name: iptables-services
          state: latest
    - shell: /usr/sbin/iptables -I INPUT 1 -p tcp -s 172.17.0.0/24 -j ACCEPT
    - shell: /sbin/service iptables save

- name: Install FFMpeg
  hosts: none
  become: True
  tasks:
      - get_url:
            url: http://cd1:81/artifactory/static/ffmpeg/ffmpeg-2.6.1-64bit-static.tar.xz
            dest: "{{ansible_user_dir}}/ffmpeg.tar.xz"
      - unarchive:
            src: "{{ansible_user_dir}}/ffmpeg.tar.xz"
            dest: /opt
            copy: no
            creates: /opt/ffmpeg-2.6.1-64bit-static/ffprobe
      - file: src=/opt/ffmpeg-2.6.1-64bit-static path=/opt/ffmpeg state=link

- name: Docker Registry Credentials (unprivileged)
  hosts: none
  become: False
  tasks:
      - name: Place configuration file into the standard account
        get_url:
          url: http://cd1:81/artifactory/static/ease/docker-registry/.dockercfg
          dest: "/home/vagrant/.dockercfg"

